title: Sajid Shaikh
logo: https://avatars.githubusercontent.com/u/44086997?v=4
description: An Enthusiastic Engineer who started programming during higher secondary school back in 2018. Explored various domains of programming which includes Front-End , Back-End, Data Engineering, currently working as a Software Engineer.
show_downloads: false
theme: jekyll-theme-minimal
social:
  github: https://github.com/shaikhsajid1111
  linkedin: https://www.linkedin.com/in/shaikhsajid1111
  twitter: https://twitter.com/shaikhsajid1111
  instagram: https://instagram.com/shaikhsajid1111
  facebook: https://facebook.com/shaikhsajid1111
  stackoverflow: https://stackoverflow.com/users/10282818/sajid
  dev: https://dev.to/shaikhsajid1111
github:
  repository_url: https://github.com/shaikhsajid1111
  is_project_page: false
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap