title: Sajid Shaikh
logo: https://avatars.githubusercontent.com/u/44086997?v=4
#description: text below image
show_downloads: false
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
social:
  github: https://github.com/shaikhsajid1111
  linkedin: https://www.linkedin.com/in/shaikhsajid1111
  twitter: https://twitter.com/shaikhsajid1111
github:
  repository_url: https://github.com/shaikhsajid1111