title: Sajid Shaikh
logo: https://avatars.githubusercontent.com/u/44086997?v=4
#description: text below image
show_downloads: false
theme: jekyll-theme-minimal
social:
  github: https://github.com/shaikhsajid1111
  linkedin: https://www.linkedin.com/in/shaikhsajid1111
  twitter: https://twitter.com/shaikhsajid1111
github:
  repository_url: https://github.com/shaikhsajid1111
  is_project_page: false